#!/bin/sh

run() {
	if ! pgrep -f "$1" ; then
		"$@"&
	fi
}

run /usr/bin/prime-offload

# Screen settings
run ~/.screenlayout/monitor.sh

# Compositor
run picom

# Xsettingsd
run xsettingsd

# Network Manager Applet
run nm-applet

# Polkit Gnome
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Wallpaper
run ./.fehbg

# Xresources
run xrdb merge .Xresources

# Low battery notifier
~/.config/awesome/scripts/low_bat_notifier.sh

# Ibus daemon
run ibus-daemon -drx

# Other
xsetroot -cursor_name left_ptr
libinput-gestures-setup start
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Disable While Typing Enabled" 0

# Syncthing
syncthing --no-browser
