#!/bin/sh

/usr/bin/prime-offload

# Compositor
picom

# Xsettingsd
xsettingsd

# Network Manager Applet
nm-applet

# Polkit Gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Wallpaper
./.fehbg

# Xresources
xrdb merge ~/.Xresources

# Ibus daemon
ibus-daemon -drx

# Auto lock
xss-lock -- ~/.config/awesome/bin/blur-lock

# Syncthing
syncthing --no-browser
