#!/bin/sh

run() {
  if ! pgrep -f "$1"; then
    "$@" &
  fi
}

run /usr/bin/prime-offload

# Xresources
run xrdb merge ~/.Xresources

# Compositor
run picom

# Xsettingsd
run xsettingsd

# Network Manager Applet
run nm-applet

# Polkit Gnome
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Wallpaper
run ./.fehbg

# Ibus daemon
ibus-daemon -drx

# Auto lock
run xss-lock -- ~/.config/awesome/bin/blur-lock

# Syncthing
run syncthing --no-browser
